### ISSUE TITLE
metadata field "type": not all options are visible in the search facet

### ISSUE THREAD

**Issue by hirschlisa** [cessda/cessda.training-resources.issues#47]
In the search facet on the left hand side of https://www.cessda.eu/Training-Resources it is possible to select the type of resource. The list that you can pick from there is not the entire list - some categories that exist according to https://docs.google.com/spreadsheets/d/1XgybB2cAcaCT9Ao8Bj2U3B_58GcbFd9B/edit?gid=371774281#gid=371774281 (poster, publication, podcast, game, software) cannot be selected. This might be becuase they have not occured yet in the resources.

Is it possible to include all categories (even if they do not yield any results)? Or are only categories shown in the search facet that exist and this list would autoimatically be updated if we included a podcast for example? @openconcept do you have any more insights on how this works?

**Comment by openconcept** [comment]
Categories that have not been used for any resources are not listed as search/filter criteria. This is by design, because it is good UX practice to avoid presenting options that are known to yield zero results. If you wish to expose all possible values, it would be a better option to publish the metadata schema in a reader-friendly format on a dedicated page.

**Comment by hirschlisa** [comment]
thanks for the info, all good then!
